<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.fascesaedi</groupId>
        <artifactId>kanketsu-parent</artifactId>
        <version>1.0.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>kanketsu-examples</artifactId>
    <packaging>jar</packaging>

    <properties>
        <jmh.version>1.37</jmh.version>
        <uberjar.name>benchmarks</uberjar.name>
        <maven.deploy.skip>true</maven.deploy.skip>
        <maven.install.skip>true</maven.install.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.fascesaedi</groupId>
            <artifactId>kanketsu-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.fascesaedi</groupId>
            <artifactId>kanketsu-repl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.fascesaedi</groupId>
            <artifactId>kanketsu-logging</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>